### ISSUE TITLE
(gitlab-runner) new package version

### ISSUE THREAD

**Issue by ViceIce** [majkinetor/au-packages#103]
Runner v11.6.1 is available.

https://gitlab.com/gitlab-org/gitlab-runner/tags/v11.6.1
https://gitlab.com/gitlab-org/gitlab-runner/commit/8d8299751972f769b55288d36a354139bdb7dcfe

https://gitlab-runner-downloads.s3.amazonaws.com/v11.6.1/binaries/gitlab-runner-windows-amd64.exe
https://gitlab-runner-downloads.s3.amazonaws.com/v11.6.1/binaries/gitlab-runner-windows-386.exe

**Comment by majkinetor** [comment]
I fixed it but it uses official [changelog](https://gitlab.com/gitlab-org/gitlab-runner/raw/master/CHANGELOG.md) for version discovery where 1.6.1 is not mentioned. This change will update it to 1.6.0.

**Comment by ViceIce** [comment]
Thanks.

Maybe it would be a good idea to use the git tags to find a new version. From the tag you will find the correct changelog.
