### ISSUE TITLE
Package rundeck: Error when tried to uninstall

### ISSUE THREAD

**Issue by sboulianne** [majkinetor/au-packages#105]
Can you fix your uninstall/upgrade script ASAP ?
choco uninstall rundeck
Chocolatey v0.10.12-beta-3-gb65f586
Uninstalling the following packages:
rundeck
Removing 'exp' and 'lib' folders from 'C:\rundeck\server'
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\rundeck\server\exp' because it does not exist.

rundeck v3.0.16
Removing C:\rundeck
Removing environment variable
Skipping auto uninstaller - No registry snapshot.

I have the same error when I tried to upgrade.
Removing 'exp' and 'lib' folders from 'C:\rundeck\server'
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\rundeck\server\exp' because it does not exist.

**Comment by majkinetor** [comment]
There is no such thing as ASAP here. For ASAP you will have to donate.

Given its mostly irrelevant for most users and that package is not really meant to be much upgradable which is mentioned in notes I may look into it when I find time.

**Comment by majkinetor** [comment]
This is actually already fixed. It is not backward compatible tho - it will work correctly once you installed 3.x version.
