### ISSUE TITLE
(pass-winmenu) Restarting programs breaks in multi-user user environment

### ISSUE THREAD

**Issue by AeliusSaionji** [majkinetor/au-packages#113]
https://github.com/majkinetor/au-packages/blob/714b5576c30e0961d3f2eb5576a14e6217e7e3d9/pass-winmenu/tools/chocolateyInstall.ps1#L35

Not a big issue, but when the administrator is a separate account, this causes pass-winmenu to be run as the administrator and not the user. Thus it does not find my `$HOME\.password-store`.

Also- does this need to go into C:\tools? Why not install to toolsdir?

**Comment by AeliusSaionji** [comment]
Along the same vein, the script creates the `.password-store` folder in an account that is not mine.

**Comment by majkinetor** [comment]
Yeah, I know about it, but that is probably true for bunch of other non-trivial packages. I think the scenario you mention is rare and benefits of not having to think about that are great IMO.

I thought about this before and I think this can't be easily fixed.

> Along the same vein, the script creates the .password-store folder in an account that is not mine.

You can use package param, but again, the dir wont be readable by other user

> Also- does this need to go into C:\tools? Why not install to toolsdir?

Perhaps, but *need to* based on what ? Is there a difference ?

**Comment by AeliusSaionji** [comment]
Perhaps a package parameter which would skip these sections if true? I could make the PR if you'd like.

> Perhaps, but need to based on what ? Is there a difference except permission details ?

It's just nice to follow convention. Chocolatey installs things to programdata. `c:\tools\` exists as an exception for programs which don't like being there. I guess I would ask: what is the reason for defying convention?

**Comment by AeliusSaionji** [comment]
I suppose it is possible that Baggykiin might introduce an update which expects write access to the config- and this documented behavior expects write access to the working directory:
> You can always generate a new configuration file, containing all settings and their default values, by renaming or deleting the old one and starting pass-winmenu.
