### ISSUE TITLE
(plantuml) use openjre

### ISSUE THREAD

**Issue by BigBlueHat** [majkinetor/au-packages#118]
Similar to #108 for yed, but this one's for plantuml. 😃 Thanks for making these packages available!

**Comment by BigBlueHat** [comment]
Maybe switching from `javaruntime` to [`openjdk`](https://chocolatey.org/packages/openjdk) would do the trick:
https://github.com/majkinetor/au-packages/blob/82f31a8386d1c28e6b5d02ba773e1cbf876fbbb3/plantuml/plantuml.nuspec#L51

I'm not familiar with testing these packages...or I'd just send a PR... Hopefully it's an easy change, though!

**Comment by majkinetor** [comment]
We don't need JDK  for this package (since its overkill) but JRE.

**Comment by BigBlueHat** [comment]
Sure. Mainly wanting to avoid the "Oracle license has changed" notifications--when they can be avoided.

**Comment by majkinetor** [comment]
I can do this as soon as I find suitable replacement. I will follow what eventually gets resolved here:

https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1315
