### ISSUE TITLE
(new-package) postgresql

### ISSUE THREAD

**Issue by majkinetor** [majkinetor/au-packages#122]
Should be done with streams and produce multiple packages (9,10,11).
Metapackage should target 11, currently targets 10.

- https://chocolatey.org/packages/postgresql
- https://chocolatey.org/packages/postgresql9
- https://chocolatey.org/packages/postgresql10
- https://chocolatey.org/packages/postgresql11
- https://chocolatey.org/packages/postgresql12

**Comment by majkinetor** [comment]
Added virtual streams to `postgresql`.

Now, its equivalent:

- cinst postgresql --version 9.6.15
- cinst postgresql9 --version 9.6.15


0b9952275feb130ad99e3df659b214fceffdf654
ccc0d02a6c748ba7908ecbc879796581dc8455ff
e96495c2824c266912db94c7786a8ba2ac39577a

**Comment by majkinetor** [comment]
All streams fails verifier.

I found out that during postgre installation on chocolatey test environment one executable doesn't work due to vcredist problems (`"getlocales.exe : child killed: unknown signal"`). Running this exe manually complains that vcredist is not installed.

When postgre tries to install vcredist on its own (via param install_runtimes 1), the update fails. It fails because it tries on its own to install `kb2999226` which complains that it is not adequate for the platform.

I added dependency to vcredist140 which makes the install work on chocolatey test environment but after it is restarted.

This is also evident from the following message
https://gist.github.com/choco-bot/ab01c91c86eef277043872d8403ce3fb#file-install-txt-L2771-L2773

```
Packages requiring reboot:
2019-10-04 10:54:35,592 2924 [WARN ] - - kb2999226 (exit code 3010)
```

This means that packages should be exluded from verification.

**Comment by karlhorky** [comment]
@majkinetor Is the `postgresql` version `12.0` installer ignoring the password flag? I tried running it like this:

```sh
choco install postgresql --params '/Password:postgres'
```

After the install, I tried logging in as `postgres` with the password `postgres`, but it didn't let me in. There was also no extra password in the installation output, as far as I could see :(

---

One further question too: after installing for the first time, I tried to reinstall the same version **without a password**, but Chocolatey completed right away without any output of a password.

In the end I had to downgrade to another version so that it would show the password in the output.

Is this a bug? And if so, should I file this somewhere?

**Comment by majkinetor** [comment]
With virtual package you need to use

```
cinst postgresql --params '/Password:test' --paramsglobal
```

otherwise, use `postgresql12`.

I added that to Notes.

> There was also no extra password in the installation output, as far as I could see :(

There is warning
https://github.com/majkinetor/au-packages/blob/master/postgresql/tools/chocolateyInstall.ps1#L4-L7

If you think there is a bug provide complete output.

**Comment by karlhorky** [comment]
Ah, `--paramsglobal` is required, understood! Would it be possible to get an example of both of these lines below in the **Package parameters** section of [the package page](https://chocolatey.org/packages/postgresql)?

```sh
cinst postgresql12 --params '/Password:test'
cinst postgresql --params '/Password:test' --paramsglobal
```

**Comment by karlhorky** [comment]
> If you think there is a bug provide complete output.

Here's the output of **reinstallation** after having `postgresql` already installed and then uninstalled once:

```sh
$ choco install postgresql --version=11.5
Chocolatey v0.10.15
Installing the following packages:
postgresql
By installing you accept licenses for the packages.
Progress: Downloading postgresql 11.5... 100%
postgresql v11.5 [Approved]
postgresql package files install completed. Performing other installation steps.
The install of postgresql was successful.
 Software install location not explicitly set, could be in package or
 default install location if installer.
Chocolatey installed 1/1 packages.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

**Comment by majkinetor** [comment]
That is strange, output is missing all information (not only pasword but log file location). You shoul give output with parameter `-d` (debug).

I just tried your command, it shows password even before starting to download files:

```
master~> choco install postgresql --version=11.5
Chocolatey v0.10.15
Installing the following packages:
postgresql
By installing you accept licenses for the packages.
Progress: Downloading postgresql11 11.5... 100%
Progress: Downloading postgresql 11.5... 100%

postgresql11 v11.5 [Approved]
postgresql11 package files install completed. Performing other installation steps.
WARNING: You did not specify a password for the postgres user so an insecure one has been generated for you. Please change it immediately.
WARNING: Generated password: a2cec27501d6440382716656d1ab5af2
Using system proxy server '10.35.2.75:7999'.
Downloading postgresql11 64 bit
  from 'https://get.enterprisedb.com/postgresql/postgresql-11.5-2-windows-x64.exe'
Using system proxy server '10.35.2.75:7999'.
Progress: 24% - Saving 45.44 MB of 189.02 MB
```

It wont show password if it is provided, but in this case it isn't propagated to postgresql11 package so it shows.

**Comment by majkinetor** [comment]
This is probably virtual package quirk of some kind. Try using major postgrepackage, in your case `postgresql11`.

**Comment by karlhorky** [comment]
> I just tried your command, it shows password even before starting to download files
> It wont show password if it is provided, but in this case it isn't propagated to postgresql11 package so it shows.

Yes, this is true for the **first install**. My output was after `choco uninstall postgresql --version=11.5`.

**Comment by karlhorky** [comment]
I will try with `postgresql11` to see if it helps.

**Comment by karlhorky** [comment]
I tried installing `postgresql11` after uninstalling using `choco uninstall postgresql --version=11.5`, and it gives me an error that it's already installed:

```sh
User@DESKTOP-9SDKD4E MINGW64 ~
$ choco uninstall postgresql --version=11.5
Chocolatey v0.10.15
Uninstalling the following packages:
postgresql
postgresql v11.5
Skipping auto uninstaller - No registry snapshot.
postgresql has been successfully uninstalled.
Chocolatey uninstalled 1/1 packages.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

User@DESKTOP-9SDKD4E MINGW64 ~
$ choco install postgresql11
Chocolatey v0.10.15
Installing the following packages:
postgresql11
By installing you accept licenses for the packages.
postgresql11 v11.5 already installed.
Use --force to reinstall, specify a version to install, or try upgrade.
Chocolatey installed 0/1 packages.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Warnings:
- postgresql11 - postgresql11 v11.5 already installed.
Use --force to reinstall, specify a version to install, or try upgrade.
```

---

I continued by using `choco install postgresql11 --force`, which installed it from the start, which **showed the password** 🎉.

---

I then proceeded to `choco uninstall postgresql11` and then `choco install postgresql11`, which gave me the following output **also with the new generated password**! 🎉

```sh
$ choco install postgresql11
Chocolatey v0.10.15
Installing the following packages:
postgresql11
By installing you accept licenses for the packages.
Progress: Downloading postgresql11 11.5... 100%
postgresql11 v11.5 [Approved]
postgresql11 package files install completed. Performing other installation steps.
The package postgresql11 wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): y
WARNING: You did not specify a password for the postgres user so an insecure one has been generated for you. Please change it immediately.
WARNING: Generated password: 1abaa2c2e55347679e2b946055536300
Downloading postgresql11 64 bit
 from 'https://get.enterprisedb.com/postgresql/postgresql-11.5-2-windows-x64.exe'
Progress: 100% - Completed download of C:\Users\User\AppData\Local\Temp\chocolatey\postgresql11\11.5\postgresql-11.5-2-windows-x64.exe (189.02 MB).
Download of postgresql-11.5-2-windows-x64.exe (189.02 MB) completed.
Hashes match.
Installing postgresql11...
postgresql11 has been installed.
Installation log: C:\Users\User\AppData\Local\Temp\chocolatey\install-postgresql.log
Iinstalled to 'C:\Program Files\PostgreSQL\11'
 postgresql11 may be able to be automatically uninstalled.
The install of postgresql11 was successful.
 Software installed to 'C:\Program Files\PostgreSQL\11'
Chocolatey installed 1/1 packages.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

---

So it appears that the problem is **only** with a **reinstall** of **the virtual package `postgresql`** - it works properly with a version number like `postgresql11`.

@majkinetor Should I submit a bug for the virtual package?

**Comment by karlhorky** [comment]
So it appears that the problem is **only** with a **reinstall** of **the virtual package `postgresql`** - it works properly with a version number like `postgresql11`.

@majkinetor Should I submit a bug for the virtual package?

**Comment by majkinetor** [comment]
I think there is nothing we can do here really so this is not a bug, its choco design.

Here are some examples:

```ps1
 cinst postgresql --params /Password:test --paramsglobal

# This wont work, only virtual package itself is replaced
 cinst postgresql --force

# This kinda works, but also reinstalls `vcredist140` which sux.
cinst postgresql --force --force-dependencies

# This uninstalls only postgresql virtual package leaving postgresql12 as is
cuninst postgresql

# This uninstalls all
cuninst postgresql12 postgresql
```

Perhaps @gep13 @ferventcoder @admiringworm could offer some ideas. What is probably needed here is to behave like .portable or .install packages which when uninstalled prompt for removal of dependent package.

**Comment by majkinetor** [comment]
Added notes about all of this here:

https://github.com/majkinetor/au-packages/blob/master/postgresql/README.md#virtual-package

**Comment by karlhorky** [comment]
> Here are some examples:

Thanks, very illuminating!

Is there any possibility that we could have that also on [the official package page](https://chocolatey.org/packages/postgresql)?

I would do a pull request for this if it is open source... Maybe also with some further examples of correct usage with version number like `cinst postgresql12`.

**Comment by majkinetor** [comment]
> Is there any possibility that we could have that also on the official package page?

Anything in the README.md will be there on next update, its automatic. I added some details there.

> I would do a pull request for this if it is open source...

Its open source

**Comment by karlhorky** [comment]
Ah ok, understood! Didn't know that the contents of the chocolatey.org page comes from this repository. Then we don't need to do a different pull request for that.
