### ISSUE TITLE
(postgresql) Missing dependency for 9.6.15

### ISSUE THREAD

**Issue by michaelin** [majkinetor/au-packages#134]
Installation of postgresql 9.6.15 fails with the error message:

> error running C:\Users\Administrator\AppData\Local\Temp;\postgresql_installer_38324d7a3d\getlocales.exe : child killed: unknown signal

After a bit of digging, i found a [forum post](https://postgresrocks.enterprisedb.com/t5/PostgreSQL/PostgreSQL-installation-issues/m-p/4142/highlight/true#M366) describing the cause of the problem: Missing Visual Studio 2013 redistributables

This package depends on vcredist140, which does not include the 2013 redistributabels. Installing the vcredist2013 before installing postgresql solved the problem.

Is it possible to add conditional dependencies, so that vcredist2013 will be installed for versions that require it? Or maybe to add the 2013 redistributables to the vcredist140 package?

**Comment by majkinetor** [comment]
Yes, it is possible.

Can you check if the postgresql 9.6 requires ONLY vcredist2013 ?

**Comment by majkinetor** [comment]
Also, is that for all v9 versions ?

**Comment by majkinetor** [comment]
Closed due to no feedack.

**Comment by dev0-cup** [comment]
![install-error-postgresql9 6 19-1-windows-x64](https://user-images.githubusercontent.com/54296312/94757223-14ec6c80-03b3-11eb-9789-5e4f96db649e.png)

I have same issue on Windows 7 64 bit when installing PostgreSQL9.6.19-1-windows-x64.exe
Please let us know solution.

Thanks in advance!

**Comment by majkinetor** [comment]
Have you tried `cinst vcredist2013`

**Comment by dev0-cup** [comment]
Hi,

Thanks for your response.
PostgreSQL v8, 9 and 10 have same issue like above image.
PostgreSQL v11 and 12 have no issue like that.
But when i try to create new database in 12 version, i get error like:
![Uploading rolcatupdate_error.png…]()

**Comment by majkinetor** [comment]
That didn't answer my question :)

**Comment by gidiasamoah** [comment]
I'm facing the same issue here
