### ISSUE TITLE
New update causing Chocolatey issues

### ISSUE THREAD

**Issue by ImportTaste** [majkinetor/au-packages#138]
I've upgraded Etcher through chocolatey on this installation before, this is the first time it's failed.

Here's the log of `choco upgrade etcher --debug --verbose -y` from admin-level PowerShell 5.1:
[chocolatey.log.zip](https://github.com/majkinetor/au-packages/files/3945872/chocolatey.log.zip)

Changed my username to ABCXYZ through Find/Replace but it's otherwise unaltered.

**Comment by ImportTaste** [comment]
It successfully upgrades now, seemingly due to magic.

**Comment by majkinetor** [comment]
Yeaah, AU is magical I agree. 🥇 :)
