### ISSUE TITLE
Multi thread (with multi GPU)

### ISSUE THREAD

**Issue by T0MuX** [majkinetor/au-packages#144]
Hi, this is not really an issue, this is a kind of feature request / feedback.

At work, we have a CAVE (a big computer for 3D applications like ANSYS, OPTIS, ART, and such). The CAVE is composed of 3 videoprojectors (as screens), each plugged on one only graphic card (this means there is one graphic card for each videoprojector, so one gpu for each)...

We are facing issues when running our 3D applications, then I have to test the whole hardware. But, when I launch FurMark, I have only 1 of 3 GPUs burning. I tried many funny tests like run one furmark instance per screen, but only the 1st gpu is working. I would like to challenge the 3 gpu in the same time.

Let me know if it's scheduled for further version or not, thank you :) 

Kind regards

**Comment by majkinetor** [comment]
U should direct your question upstream, this is a package repository.
