### ISSUE TITLE
Make etcher internal

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [majkinetor/au-packages#158]
It would be nice if etcher was changed to be an internal package. 

Now that it only has a single build, instead of x32 and 64, it is under 200mb. The license is apache 2, so no problems there.

**Comment by majkinetor** [comment]
Yeah, but then again https://github.com/chocolatey/chocolatey.org/issues/613

**Comment by TheCakeIsNaOH** [comment]
Alright, I'll close for the moment this due to that issue, but I'll come back if that ever gets resolved.

**Comment by majkinetor** [comment]
Sure. I also keep only embedded packages if possible. 

That issue is almost 2 years old so I don't think it will get resolved soon. Probably MS new tool winget will get more capable faster then choco team fixes this.

**Comment by TheCakeIsNaOH** [comment]
Sigh, yeah. I probably should look into how hard it would be to create an offline repository for winget.

---

Also, you might have an interest in this:
https://github.com/TheCakeIsNaOH/choco-remixer

It is still under development, but it is an alternative to the C4B package internalizer.

**Comment by majkinetor** [comment]
Thanks for the link. 

I do not need such tool tho - I personally made embedded packages much more prominent and trivial to make both with AU features and by making it required on coreteam repo. I almost never use non embedded packages . The worked so far flawlessly, you can count on them long term and you don't even need a choco gallery as with AU they are published on github releases.

**Comment by TheCakeIsNaOH** [comment]
Yes, thank you very much for AU, it is wonderful. As is your work on making packages internal.

**Comment by ferventcoder** [comment]
It's likely quite easy to stand back and complain when one doesn't understand the intricacies/complexities of the issue. There has been a lot of effort put into ensuring the Chocolatey Community Repository can handle double the number of requests year over year. 

In 2014, we had maybe 10M requests per day. In 2016 it was around 15M per day. In 2018 it was around 30M per day. Yesterday we were near 72M requests. In 24 hours. I'm sorry, but if you believe what worked on the site 2 years ago at half as many requests per day could possibly even run under the kind of load we have today, I'm not sure what to tell you.

We will continue working to support this and have been working to make things better over time so we could get things working for embedded packages on every push. 

It would be nice if you have an issue @majkinetor if you could bring it directly to me first - I don't do well with passive aggressive comments like these and I don't find it conducive to good community behavior.

**Comment by majkinetor** [comment]
> I don't do well with passive aggressive comments like these and I don't find it conducive to good community behavior.

I can totally live with that. I am equally disappointed.

**Comment by ferventcoder** [comment]
> I am equally disappointed.

Understood, I am quite disheartened that this has been very difficult to find and fix permanently.

**Comment by TheCakeIsNaOH** [comment]
Since I think it is fixed, I'll reopen this.
