### ISSUE TITLE
 (cpu-z.portable) Error on install 

### ISSUE THREAD

**Issue by Hlsgs** [majkinetor/au-packages#172]
When trying to install the `cpu-z.portable` package using Choco that is portable itself, I get the following:
```
ERROR: Cannot bind argument to parameter 'Path' because it is null.
```

**Comment by majkinetor** [comment]
Try now: `cinst cpu-z.portable --version 1.94.0.20201209 -force`

**Comment by Hlsgs** [comment]
> 
> 
> Try now: `cinst cpu-z.portable --version 1.94.0.20201209 -force`

That works. But why is it only grabbing only the x64 version and not both x64 and x32, like a "normal" CPU-Z portable download?

**Comment by majkinetor** [comment]
There were never 2 versions, it was just an illusion :)

**Comment by majkinetor** [comment]
This is from older one:

![image](https://user-images.githubusercontent.com/85767/101630020-8b948e80-3a22-11eb-9ed6-239ef90b9fce.png)

**Comment by Hlsgs** [comment]
The official portable download for 1.94 comes with two binaries:
`cpuz_x32.exe` SHA1: `CEDDFDC60EDBD0D5CE24FBA12752F42E137BBD37`
`cpuz_x64.exe` SHA1: `111D5ADE416485D1F367815592CFC5DE6C52D9CA`

Your package has just:
`cpuz.exe` SHA1: `38D895D1AA2C12D618275EE02DF926A7FF53C079`
so it's neither of the above.

What's going on here?

**Comment by majkinetor** [comment]
The other one gets removed the same as before, that wasn't changed:

![image](https://user-images.githubusercontent.com/85767/101636151-31e49200-3a2b-11eb-95dd-a32802790e66.png)

**Comment by Hlsgs** [comment]
Hmm, two questions then:

1. Why would it's hash change from `cpuz_x64.exe` jsut by moving and renaming it?
2. Why not leave both? If it's portable why shouldn't it work on an x86 OS too, in case of dual-boot, for example?

**Comment by majkinetor** [comment]
To have other arch is pointless as its not on the PATH, most users would never find it or know how to execute it. Alternative is to shim by full name which is stupid as most people don't need 2 arch.

Do you have a problem or you just nitpick ?

**Comment by majkinetor** [comment]
> Why would it's hash change from cpuz_x64.exe jsut by moving and renaming it?

It wouldn't :)

**Comment by Hlsgs** [comment]
> 
> 
> To have other arch is pointless as its not on the PATH, most users would never find it or know how to execute it. Alternative is to shim by full name which is stupid as most people don't need 2 arch.
> 
> Do you have a problem or you just nitpick ?

I'm doing some fairly convoluted stuff with simlinks to automate the creation of USB sticks with tools I use, so not nitpicking, but far from your avereage usage scenario. I'll just rely on x64 as I will hopefully not be seeing many 32bit machines moving forward. So thanks for the fix and clarifications.



> 
> 
> > Why would it's hash change from cpuz_x64.exe jsut by moving and renaming it?
> 
> It wouldn't :)

You're right. Just downlaoded a fresh copy and they match. Authors probably changed the files without altering the version. Wouldn't be unheard of :)

**Comment by majkinetor** [comment]
> I'll just rely on x64 as I will hopefully not be seeing many 32bit machines moving forward. So thanks for the fix and clarifications.

Indeed, its better to put a nail in the coffin instead. 

> Authors probably changed the files without altering the version.

They do that on cpu-z all the time. Thats the reason updater checks  remote checksum each time, besides version. When you see FIX version its silent update:

https://github.com/majkinetor/au-packages/blob/master/cpu-z.portable/update.ps1#L24-L30

As you can see more silent then regular updates:

![image](https://user-images.githubusercontent.com/85767/101645651-e506b880-3a36-11eb-9b0b-66275f512f46.png)

**Comment by Hlsgs** [comment]
I see. Thanks again for you efforts and for the explainers!

**Comment by majkinetor** [comment]
No problem m8. Thanks for reporting this.
