### ISSUE TITLE
(yed) Incompatible with adoptopenjdkjre version 16

### ISSUE THREAD

**Issue by jedfrechette** [majkinetor/au-packages#182]
After upgrading to the latest adoptopenjdkjre, currently 16.0.0.36, parts of yed's GUI (version 3.21.1) are broken. In particular the main menu is missing. Incompatibility with Java versions after 15 seems to be confirmed by this forum post:

https://yed.yworks.com/support/qa/22413/is-yed-compatible-with-java-build-251

**Comment by majkinetor** [comment]
Yeah, I can confirm that. Not sure what to do, perhaps to wait a bit on it to get fixed on upstream or remove dependency and let people choose whatever they want and create shortcut via whatever javaw available on the PATH.

I just installed `javaruntime` and remove path from the shortcut (left only javaw.exe) and it works.

**Comment by majkinetor** [comment]
I used jre8 as dependency.

**Comment by majkinetor** [comment]
FYI I will return this to adoptopenjdkjre as it now it doesn't work with JRE.
