### ISSUE TITLE
Signal 5.7.0 installed via chocolatey is broken

### ISSUE THREAD

**Issue by pshem** [majkinetor/au-packages#185]
See also https://github.com/signalapp/Signal-Desktop/issues/5388
Happened to me, probably because I did not disable updates through the application (It's a package installation flag)

**Comment by majkinetor** [comment]
I dont see anything for me here.

**Comment by pshem** [comment]
For me and at least one more person who had signal installed via chocolatey and didn't disable in-app updates, Signal stopped starting yesterday/today. I was unable to fix the issue and had to uninstall signal and reconnect the desktop app. I though I would warn other people in case we can figure out what happened. The logs in the linked main Signal repository look identical to mine

**Comment by majkinetor** [comment]
Doesn't seem like too much of a problem and its easy to resolve. There is also `NoAutoUpdate` param but if you dont' remember the install arguments it will make signal not updatable on next update.

**Comment by IL2P** [comment]
Mine broke after updating via chocolatey too. Fix for now was just install 5.8.0 via https://signal.org/download/windows/# and all seems to be working
