### ISSUE TITLE
(winsw) outdated

### ISSUE THREAD

**Issue by majkinetor** [majkinetor/au-packages#195]
There were some packaging changes, no longer has zip, will wait a bit.

**Comment by MTSym** [comment]
Hey there!

Is there a chance that you update the package to the latest version in any time soon? If I interpret your code correct you already did the changes to use the .exe files instead of .zip.

**Comment by majkinetor** [comment]
This is automatic package that is blocked as latest version is 2.12.

Once they release new one it will get updated. 

See here for details:
https://gist.github.com/majkinetor/a700c70b8847b29ebb1c918d47ee4eb1#winsw

Unfortunately  I don't have time to manually handle it.
