### ISSUE TITLE
(postgresql) Outdated

### ISSUE THREAD

**Issue by majkinetor** [majkinetor/au-packages#201]
Postgresql packages can't get pushed (not embedded):

> Repeating postgresql (1): System.Management.Automation.RuntimeException: Chocolatey v0.10.15 Attempting to push postgresql14.14.1.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql13.13.5.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql.13.5.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql12.12.9.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql.12.9.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql11.11.14.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql.11.14.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql10.10.19.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql.10.19.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql9.9.6.24.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql.9.6.24.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql.14.1.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository.
Ignoring postgresql (2): System.Management.Automation.RuntimeException: Chocolatey v0.10.15 Attempting to push postgresql14.14.1.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql13.13.5.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql.13.5.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql12.12.9.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql.12.9.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql11.11.14.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql.11.14.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql10.10.19.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql.10.19.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql9.9.6.24.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql.9.6.24.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository. Chocolatey v0.10.15 Attempting to push postgresql.14.1.1.nupkg to https://push.chocolatey.org An error has occurred. It's possible the package version already exists on the repository.

It happens for several days on each try. Packages DO NOT exist and they work (tested in Windows Sandbox)

Not sure what to do about it, but people already started complaining...

/cc @gep13 @admiringworm

**Comment by gep13** [comment]
@majkinetor looking at the logs, this seems to be an issue with the description of the package:

> 13 Nov 2021 17:17:29.576173 <135>1 2021-11-13T17:17:28.269+00:00 app web.4 - - A nuget package's Description property may not be more than 4000 characters long.

This will need to be reduced before the package will be able to be pushed.

**Comment by majkinetor** [comment]
All packages are pushed now. Thanks @gep13. Consider more length there, or consider compiled markdown length (in my case lots of URLs did eat up). I removed valuable info to fit.

https://gist.github.com/majkinetor/a700c70b8847b29ebb1c918d47ee4eb1#postgresql14

**Comment by gep13** [comment]
@majkinetor there are no immediate plans to increase the character limit of the description field, however, there are some other thoughts in this area, but nothing has been decided yet.  Thanks for getting those packages updated!
