### ISSUE TITLE
(gitlab-runner) Attempts to install git 2.12.2, when a later version of git is already installed

### ISSUE THREAD

**Issue by rasa** [majkinetor/au-packages#203]
Shouldn't this be updated:

https://github.com/majkinetor/au-packages/blob/1e442aeb2b48bc3dbd10460341677f7df1f5d827/gitlab-runner/gitlab-runner.nuspec#L60

**Comment by majkinetor** [comment]
i don't know. Should it ?

**Comment by rasa** [comment]
The reason I ask is that I already had git 2.33 installed, but choco tried to install 2.12.2 on top of it. I know this is a choco bug, but it was driven by this setting.

**Comment by majkinetor** [comment]
Choco shouldn't install older stuff. Upstream problem. Feel free to PR latest git nevertheless.
