### ISSUE TITLE
Signal installed/upgraded but parameters ignored

### ISSUE THREAD

**Issue by 360path** [majkinetor/au-packages#207]
I have Chocolatey GUI 0.19.0.0 installed and upgraded Signal to 5.28.0 and noticed that it did not apply the parameters `NoAutoUpdate` and `NoShortcut` seem to have been ignored. I don't know whether this was already the case with previous versions, but I noticed just now. This means, no corresponding entry in the host file was created and a desktop shortcut was placed.

How can I check (and edit) the supposed parameters on install/upgrade of a package when using the community repository?

**Comment by majkinetor** [comment]
U should use  `--use-remembered-arguments` but I think it sometimes doesn't work correctly (not sure tho).

https://github.com/chocolatey/choco/issues/797

**Comment by 360path** [comment]
Thank you for the information!

I have `useRememberedArgumentsForUpgrades` turned on.

Is there a way to add arguments in Chocolatey GUI during install and/or upgrade of a package? Or do I have to go into CLI for that?

**Comment by majkinetor** [comment]
I don't use GUI, can't help you with that.

**Comment by gep13** [comment]
> @360path said...
Is there a way to add arguments in Chocolatey GUI during install and/or upgrade of a package? 

There is an issue in the Chocolatey GUI repository to provide this functionality, and it should ship in the next version of Chocolatey GUI which will ship early this year:

https://github.com/chocolatey/ChocolateyGUI/issues/545

> @majkinetor said...
Its not flipped on by default AFAIK so far although its years it was introduced. I wonder when will it happen

We have recently discussed this very issue, and this will be flipped on by default once we close out the last remaining issue with this particular feature, and monitor it for any further issues.  There is an open PR for the last known issue here:

https://github.com/chocolatey/choco/pull/2484

**Comment by 360path** [comment]
@gep13 said:
> > @360path said...
> > Is there a way to add arguments in Chocolatey GUI during install and/or upgrade of a package?
> 
> There is an issue in the Chocolatey GUI repository to provide this functionality, and it should ship in the next version of Chocolatey GUI which will ship early this year:
> 
> [chocolatey/ChocolateyGUI#545](https://github.com/chocolatey/ChocolateyGUI/issues/545)

Thanks for pointing that out. Looking forward to that feature.

Meanwhile, maybe you can help with this or point me to somewhere I could get an answer: so, I used the CLI and passed the arguments. But as I already was on the latest version, it probably did nothing (at least, no Hosts file edit was performed). How can I check/make sure that next time `upgrade` is called for Signal (or any specific package for that matter), `useRememberedArgumentsForUpgrades` should be invoked and the previous arguments/parameters used again?

**Comment by gep13** [comment]
The persisted arguments are stored in the `.chocolatey` folder, which you can find here:

```
C:\ProgramData\chocolatey\.chocolatey
```

In there, there should be a folder for the Signal package that you just installed, and in that folder, there should be a `.arguments` file.  This is where the persisted arguments are stored, however, they will be encrypted.  There isn't an "easy" way to unencrypt these today, however, that is a new feature that will be shipping in the next version of Chocolatey GUI.

**Comment by majkinetor** [comment]
I wrote above:

> but I think it sometimes doesn't work correctly (not sure tho).

Now I see this is related to open PR @gep13 mentioned, and until it is merged, mass update is basically unusable.
