### ISSUE TITLE
(postgresql) Install Arguments are ignored

### ISSUE THREAD

**Issue by pushrbx** [majkinetor/au-packages#212]
If I run the following in a powershell comand prompt:     
`choco install postgresql --ia '--enable-components commandlinetools'`     

`choco install postgresql --ia '--disable-components server,stackbuilder,pgAdmin'`

In both cases it just installs everything.

If I run the installer file directly:
`postgresql-14.2-1-windows-x64.exe --mode unattended --unattendedmodeui minimal--enable-components commandlinetools`
It installs everything. But if run in with `--disable-components` it works:
`postgresql-14.2-1-windows-x64.exe --mode unattended --unattendedmodeui minimal --disable-components server,stackbuilder,pgAdmin`

I think this problem only applies on the latest installers of postgresql.

**Comment by majkinetor** [comment]
I think its known upstream issue. It seems that solution is to later uninstall stuff u dont need

**Comment by pushrbx** [comment]
I think a note would be nice somewhere to let people know that "there is a known upstream issue atm". I read in the issues that there is a hard limit on the character count in the README.md, so probably during install there should be a note to state this. What do you think?

**Comment by majkinetor** [comment]
I added a note for now. This can be fixed in package installer nevertheless, if somebody is up for it.
