### ISSUE TITLE
(PostgreSQL) Datadir with spaces parameter passing error

### ISSUE THREAD

**Issue by Niyakiy** [majkinetor/au-packages#214]
So during the attempt to pass PG datadir option pointing to something like c:\Program Files\PG\data (note spaces in path)
like: 
`choco install -y --no-progress 'postgresql12' --params "/Password:$DefaultPostgresPassword" --ia "--datadir $postgresqlDataDir"`

where $postgresqlDataDir is set to "c:\Program Files\PG\data"

we're getting such error:
ERROR: Running ["C:\Users\Administrator\AppData\Local\Temp\2\chocolatey\postgresql12\12.10.2\postgresql-12.10-2-windows-x64.exe" --install_runtimes 0 --superpassword ******** --enable_acledit 1 --unattendedmodeui none --mode unattended --datadir c:\Program Files\PG\data] was not successful. Exit code was '1'. See log for possible error messages.

next log messages indicate there was an issue with parsing params
2022-05-06 08:50:13,063 840 [INFO ] - VERBOSE: There has been an error.
2022-05-06 08:50:13,063 840 [INFO ] - VERBOSE: Expected option but got "Files". Options start with a leading "--" prefix

seems space in the path breaks parameters parsing and must be somehow escaped/quoted in order to prevent failures.

**Comment by majkinetor** [comment]
This is not related to the package but about general CLI/choco usage:

Try `--ia "--datadir '$postgresqlDataDir'"`

Sometimes this is hard to make it work, depending on underlying tools, so you can convert to short name via for example [this](https://github.com/majkinetor/posh/blob/master/MM_FileSystem/Get-ShortPath.ps1) script.

**Comment by Niyakiy** [comment]
@majkinetor thanks for the quick response. I've already tried such ways to pass it:
- single quotes (`--ia "--datadir '$postgresqlDataDir'"`)
- double quotes(`--ia "--datadir `"$postgresqlDataDir`""`)
and other ways to pass it - all failed.

**Comment by majkinetor** [comment]
If I pass 

```
$postgresqlDataDir="'c:\Program Files\PG\data'"; cinst -y postgresql12 --params "/Password:$DefaultPostgresPassword" --ia "--datadir $postgresqlDataDir"
```

I get this error:

ERROR: Running ["C:\Users\WDAGUtilityAccount\AppData\Local\Temp\chocolatey\postgresql12\12.10.2\postgresql-12.10-2-windows-x64.exe" --install_runtimes 0 --superpassword True --enable_acledit 1 --unattendedmodeui none --mode unattended --datadir 'c:\Program Files\PG\data'] was not successful. Exit code was '1'. See log for possible error messages.

So this might be one of those cases... I suggest you use short path and let it go. Maybe somebody from choco team could help, feel free to ping them here.

**Comment by Niyakiy** [comment]
and bad luck again:

`--datadir c:\PROGRA~1\PG\DATA` 

log output:

[INFO ] - VERBOSE: The data directory must be an absolute path, containing only letters, numbers and the characters '-', '/', '.', and '_', and must be writable.

so tildas are rejected by installer validator. Might be a PostgreSQL installer bug.

**Comment by majkinetor** [comment]
Out of ideas.
