### ISSUE TITLE
Can't find Total Commander plugins in choco store

### ISSUE THREAD

**Issue by QuAzI** [majkinetor/au-packages#216]
![image](https://user-images.githubusercontent.com/1897605/174243269-94c501d4-7f39-459e-afda-cfb3ba8460db.png)

**Comment by majkinetor** [comment]
This is the problem with gallery, nothing to do with this repository. You should redirect that to chocolatey admins or ask on their discord channel or some other way.

In the meantime, the list of plugins I maintain is available here: https://github.com/majkinetor/au-packages/tree/master/tcp. AFAIK there are no other maintainers.

**Comment by majkinetor** [comment]
Tags seem to work now.

![image](https://user-images.githubusercontent.com/85767/174473130-79d2cbee-fdf8-4445-8a92-4d23f74555fb.png)
