### ISSUE TITLE
(postgres) Dependency 'postgresql14 (= 14.4.1)' does not exist

### ISSUE THREAD

**Issue by cowwoc** [majkinetor/au-packages#219]
I was able to install postgresql in the past, but now chocolatey is complaining about dependency 'postgresql14 (= 14.4.1)':

```
postgresql not installed. An error occurred during installation:
 Unable to resolve dependency 'postgresql14 (= 14.4.1)'.
```

If you take a look at the `postgresql14` package, you will notice that version 14.4.1 does not exist. Meaning, this is a server-side problem: https://community.chocolatey.org/packages/postgresql14

**Comment by cowwoc** [comment]
Further, https://community.chocolatey.org/packages/postgresql#dependencies points to https://community.chocolatey.org/packages/postgresql14/14.4.1 which returns HTTP 404.

**Comment by cowwoc** [comment]
Looks like this is related to this commit: https://github.com/majkinetor/au-packages/commit/355d2130b423e4a238fb96c59de375b0ced798c1

But I'm not sure why it did not work.

**Comment by majkinetor** [comment]
Log tells it all: https://gist.github.com/majkinetor/a700c70b8847b29ebb1c918d47ee4eb1/a09872206b37f11c3c6042d9768b18d1662b86bd#postgresql14

> The remote server returned an error: (524)

There was a problem when pushing package apparently due to internal error on chocolatey server.

**Comment by majkinetor** [comment]
FIxed it: https://community.chocolatey.org/packages/postgresql14/14.4.1
