### ISSUE TITLE
dbeaver updates recently started failing with 2022-11-08 12:27:46,197 18664 [ERROR] - ERROR: Cannot process argument transformation on parameter 'file64'. Cannot convert value to type System.String.

### ISSUE THREAD

**Issue by drdamour** [majkinetor/au-packages#223]
Getting error 

2022-11-08 12:27:46,197 18664 [ERROR] - ERROR: Cannot process argument transformation on parameter 'file64'. Cannot convert value to type System.String.

this started last month seemingly around this change https://github.com/majkinetor/au-packages/commit/a5129772b61d1b7badb80d387e8f483e5213dd5c

we use awx to winrm over and run choc from ansible, guessing this has something to do with it.

**Comment by drdamour** [comment]
hm...seems to be host specific, we have different host it ran fine on. same winver, same awx, same choco version...odd

**Comment by majkinetor** [comment]
There are stale older installer versions in chocolatey lib folder, just delete them and it will work.

**Comment by majkinetor** [comment]
It fucks up very rarely not sure why. Its partially my fault too because I use globs in installer instead of the concrete file name. I changed that recently but didn't update old pacakges. But like I sad, I got this once in last decade maybe...

**Comment by drdamour** [comment]
k we got it twice in last month, but had lotta AWX activity/changes in that time.  will keep an eye on it. thanks

**Comment by majkinetor** [comment]
OK, let me know. Twice in a month is a lot.
