### ISSUE TITLE
Why are the cpu-z checksums changing without the upstream changing version?

### ISSUE THREAD

**Issue by rgl** [majkinetor/au-packages#224]
Do you known why are the cpu-z checksums changing without the upstream changing version? Isn't that strange?

For example, like in https://github.com/majkinetor/au-packages/commit/a494dd5b7dcb8de5f075756b894df2f8276780e5?

**Comment by majkinetor** [comment]
Yes I know. 

Vendor is silently releasing it all the time. Hence, I check for the checksum change, not version change.
