### ISSUE TITLE
Choco PostgreSQL 14.6.1, 15.1.1 dependency error on windows

### ISSUE THREAD

**Issue by Alexey-Ayupov** [majkinetor/au-packages#227]
Hi,
We are installing the latest version of PostgreSQL from the choco on our images. Starting from the 15th of December we get an error:
```
postgresql not installed. An error occurred during installation:
Unable to resolve dependency 'postgresql15 (= 15.1.1)'.
or
postgresql not installed. An error occurred during installation:
Unable to resolve dependency 'postgresql14 (= 14.6.1)'
```
We have noticed that choco installer stopped downloading PostgreSQL "exe" files from https://get.enterprisedb.com/postgresql/ website.
Could you please check it?

**Comment by majkinetor** [comment]
I unlisted those 2 versions beause there was a problem with Chocolatey Gallery automation. I forgot to unlist 14.6.1 and dit that now. You need to wait for the next release.

**Comment by Alexey-Ayupov** [comment]
Thank you for the clarification, but could you please elaborate on the "You need to wait for the next release." statement?
Should I wait for the new PostgreSQL release or the choco packet release?

**Comment by majkinetor** [comment]
Next PostgreSQL release.
