### ISSUE TITLE
postgresql14 & postgresql15 needs exception for verifier due to dependency

### ISSUE THREAD

**Issue by SebastianK90** [majkinetor/au-packages#231]
Since all other postrgres packages 9,10,11,12 & 13 have an exception for the verifier, due to vcredist140 dependency.
Could you try to contact the site admins to get an exemption?

Since I'm not the maintainer I'm not allowed to do so. (I've already contacted Paul about adding an exeption, and he told me the maintainer must request that via "click 'Contact Site Admins'.")

If you could do that it would be much appreciated

Thank you so much!

**Comment by majkinetor** [comment]
I have hard time beleiving that, since both have versions that work:

![image](https://user-images.githubusercontent.com/85767/232335605-0707c9bd-1727-49f7-a611-40616087454b.png)

I can add you as maintainer if you want to try that.

**Comment by SebastianK90** [comment]
No thanks, I've to little know-how on how to manage such a complex package.

Then maybe time will help and the next versions will start verifiing again. (if the verifier may switch finally to W2019)
I just thought you could quickly ask them, as the other packages have an exemption as well.

You can do whatever you want and close this if you like.
I've done my "best" to get a solution ¯\_(ツ)_/¯

**Comment by majkinetor** [comment]
I can ask them, but it looks like I need to do that on every package release, which defeats the purpose of having it automated. I didnt ask so far either for this package, but I remember they asked something similar on other packages. I will ask them now, but not in the future as this is then problem on Chocolatey side.

**Comment by majkinetor** [comment]
Asked, for 14 and 15. I can do that for each new major version but not minor one. Lets see what will happen.

**Comment by majkinetor** [comment]
![image](https://user-images.githubusercontent.com/85767/232337164-f37a751b-5a48-49ad-8f0b-019f4f345118.png)

**Comment by majkinetor** [comment]
Still nothing after 3 days. Very responsive for such an important package...
