### ISSUE TITLE
NirLauncher using out of date sysinternals nlp

### ISSUE THREAD

**Issue by ImportTaste** [majkinetor/au-packages#234]
In the additional downloads listing, there are updated versions of the sysinternals nlp, going up to 6. The chocolatey package appears to still be using sysinternals2.nlp. It should be updated to use sysinternals6.nlp

**Comment by majkinetor** [comment]
Sure, if it gets to roll.

**Comment by majkinetor** [comment]
Yeah, sorry.

**Comment by majkinetor** [comment]
It will be there on next release.
