### ISSUE TITLE
32 or 64 bit switching

### ISSUE THREAD

**Issue by ferventcoder** [majkinetor/au-packages#24]
https://github.com/majkinetor/au-packages/blob/master/smplayer/tools/chocolateyInstall.ps1#L4

It's a bit more nuanced than that. Here is a working script for you (C4B generates this).

~~~powershell
$fileLocation = Join-Path $toolsDir 'puppet-agent-1.3.2-x86.msi'
$fileLocation64 = Join-Path $toolsDir 'puppet-agent-1.3.2-x64.msi'
if (Get-ProcessorBits 64) {
$forceX86 = $env:chocolateyForceX86
  if ($forceX86 -eq 'true') {
    Write-Debug "User specified '-x86' so forcing 32-bit"
  } else {
    $fileLocation = $fileLocation64
  }
}
~~~

**Comment by majkinetor** [comment]
Its terribly inconvenient, and smells bad. Choco should have provided a function - Is64Install or something like that.

**Comment by majkinetor** [comment]
Will add this in core.extension

`function Is64Install() { (Get-ProcesorBits 64) -and $env:chocolateyForceX86 -ne 'true' }`

**Comment by ferventcoder** [comment]
Install-ChocolateyInstallPackage is set for one architecture. It's something to be looked at at some point.

**Comment by majkinetor** [comment]
Nah, this is used outside of it many times, it needs a special function.

**Comment by ferventcoder** [comment]
agreed on a special function.
