### ISSUE TITLE
[postgresql16] password either generated or set during install not working

### ISSUE THREAD

**Issue by DWIAltonaAnalytics** [majkinetor/au-packages#244]
after successfull installation (clean installation, I used uninstall first) I can not log in to my postgresql server, not with psql or pgAdmin.
> psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  Passwort-Authentifizierung für Benutzer »Postgres« fehlgeschlagen

I did one install, where I failed to note the password (it was a bulk install of many packages) and now there seams to be no way for me to install postgresql with a working password.

During uninstall I made sure to uninstall the meta package and the actual package and the output either showed a password which did not work, or there was no waring if I provided a password to the installer which also does not work.

Do I have to uninstall and remove some remaining files from windows to get rid of some lingering files that keep the "unknown" password?

**Comment by DWIAltonaAnalytics** [comment]
after manualy removing anything in `ProgramFiles/PostgreSQL` a fresh installation used the advertised password.

**Comment by majkinetor** [comment]
For future reference, you have a not on chocolaty package what to do in that case

https://github.com/majkinetor/au-packages/tree/master/postgresql#notes
