### ISSUE TITLE
Postgres packages have not been updated in a while

### ISSUE THREAD

**Issue by mymasse** [majkinetor/au-packages#247]
In the [update status file](https://gist.github.com/majkinetor/a700c70b8847b29ebb1c918d47ee4eb1) it lists that the postgres package is ignored. Choco community has the latest version at 16.1.0 while officially postgres is at 16.4.

**Comment by majkinetor** [comment]
Yeah, it errors due to the error listed, all the time, on the runners. I personally do not have time to fix this but feel free to PR.

**Comment by adeherdt-r7** [comment]
started helping out https://github.com/majkinetor/au-packages/pull/248

But there's a problem with the package validation upstream.

**Comment by majkinetor** [comment]
There was always problem with validation. Thats on chocolatey, not this repo. As far as I remember it requres pining choco admins to exclude each new version from verification. (you could browse older versions as proof).

**Comment by majkinetor** [comment]
I moved CI to GH. Packages should be working again.
