### ISSUE TITLE
(smplayer) Wrong globbing pattern for 32bit

### ISSUE THREAD

**Issue by AdmiringWorm** [majkinetor/au-packages#27]
Looks like the globbing pattern for getting 32bit installer is wrong.
it should be changed from
```powershell
gi "$toolsDir\*win32.exe"
```

to
```powershell
gi "$toolsDir\*x32.exe"
```

noticed this when it was opened as an issue on the choco repo.
https://github.com/chocolatey/choco/issues/1149

/cc @majkinetor

**Comment by majkinetor** [comment]
Thanks. That was exactly the reason why I standardized suffixes so I dont have to change it. This slipped during refactoring of this package to use Get-RemoteFiles.
