### ISSUE TITLE
Installation fails because fzf zip files are missing

### ISSUE THREAD

**Issue by stinos** [majkinetor/au-packages#40]
Using Powershell 5.1:

```
Find-Package fzf | Install-Package -Verbose
VERBOSE: Performing the operation "Install Package" on target "Package 'fzf' version '0.16.6' from 'chocolatey'.".
VERBOSE: NuGet: Installing 'fzf 0.16.6'.
VERBOSE: NuGet: Successfully installed 'fzf 0.16.6'.
VERBOSE:
VERBOSE: CreateFolder -- Already Exists C:\Chocolatey\lib\fzf.0.16.6
VERBOSE: Taking Snapshot «C:\Chocolatey\lib\fzf.0.16.6\tools»
VERBOSE: CreateFolder -- Already Exists C:\Chocolatey\lib\fzf.0.16.6\tools
Install-Package : The archive file type is not supported.
At line:1 char:20
+ Find-Package fzf | Install-Package -Verbose
+                    ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (False C:\Chocol...s_amd64_x64.zip:String) [Install-Package], Exception
    + FullyQualifiedErrorId : UnsupportedArchive,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```
and the C:\Chocolatey\lib\fzf.0.16.6\tools directory only contains chocolateyInstall.ps1 but not the zip files (which I assume should be there). The C:\Chocolatey\lib\fzf.0.16.6 does zontain afile named fzf-0.16.6-windows_amd64_x64.zip.txt with this content:
```
C:\Chocolatey\lib\fzf.0.16.6\tools\chocolateyInstall.ps1
C:\Chocolatey\lib\fzf.0.16.6\tools\fzf-0.16.6-windows_386_x32.zip
C:\Chocolatey\lib\fzf.0.16.6\tools\fzf-0.16.6-windows_amd64_x64.zip
```

**Comment by majkinetor** [comment]
Existence is totally not the problem because they do exist, you can see that on the gallery 
https://chocolatey.org/packages/fzf

You can also download the nuget package from there and see for yourself.

`Install-Package : The archive file type is not supported.`



Can you try with just `cinst fzf`?

**Comment by majkinetor** [comment]
This is how it looks like:

```
PS > cinst fzf --force
Chocolatey v0.10.3
Installing the following packages:
fzf
By installing you accept licenses for the packages.

fzf v0.16.6 (forced) [Approved]
fzf package files install completed. Performing other installation steps.
Installing 64 bit version
Extracting C:\ProgramData\chocolatey\lib\fzf\tools\fzf-0.16.6-windows_amd64_x64.zip to C:\ProgramData\chocolatey\lib\fzf\tools...
C:\ProgramData\chocolatey\lib\fzf\tools
 ShimGen has successfully created a shim for fzf.exe
 The install of fzf was successful.
  Software installed to 'C:\ProgramData\chocolatey\lib\fzf\tools'

Chocolatey installed 1/1 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

**Comment by stinos** [comment]
Using `cinst` works ok, it's just `Install-Package` which doesn't.

**Comment by ferventcoder** [comment]
@stinos If you want to use PowerShell PackageManagement (OneGet), please ensure you are using Chocolatey-Get until the official Chocolatey provider is available. For more information, please see https://github.com/chocolatey/chocolatey-oneget/issues/5#issuecomment-275404099

**Comment by stinos** [comment]
@ferventcoder thanks! Using ChocolateyGet instead of built-in (I assume?) Chocolatey indeed makes Install-Package fzf work. I'd really wisch information around OneGet and companions was less shattered..
