### ISSUE TITLE
AU helper: find version in url

### ISSUE THREAD

**Issue by majkinetor** [majkinetor/au-packages#74]
Its quite often to have to parse url link to get the version. Function for that would be better then using split and select as it will be more bulletproof for future url changes.

**Comment by Thilas** [comment]
[Method `Get-Version`](https://github.com/majkinetor/au/blob/master/AU/Public/Get-Version.ps1) provided by AU intends to do exactly this. Especially with my last PR: https://github.com/majkinetor/au/pull/122.
