### ISSUE TITLE
(html-tidy) Dependencies

### ISSUE THREAD

**Issue by Kristinita** [majkinetor/au-packages#75]
### 1. Summary

I don't understand, why need [**dependencies for HTML-Tidy**](https://github.com/majkinetor/au-packages/blob/master/html-tidy/html-tidy.nuspec#L28-L31). Possibly, users do not need them.

### 2. Argumentation

1. Setting optional dependencies — is extra time.
1. User install [**6 more extra dependencies**](https://ci.appveyor.com/project/Kristinita/sashapelicantest/build/1.0.58/job/4s1q3a3dl501vaa1#L186).

### 3. Chocolatey 0.10.8

Yes, it would be nice, if users would have latest Chocolatey version, but users can successful install HTML-Tidy in previous Chocolatey versions.

### 4. VCRedist

I don't find documentation, that users must have latest VCRedist for HTML-Tidy usage.

### 5. Do not offer

Yes, I know [**`--ignoredependencies` parameter**](https://github.com/chocolatey/choco/wiki/CommandsInstall#options-and-switches). And I can success install HTML-Tidy with this parameter ([**example**](https://ci.appveyor.com/project/Kristinita/sashapelicantest/build/1.0.94/job/qo638ne8rufescmk)).

Thanks.

**Comment by majkinetor** [comment]
Chocolatey 10.0.8 is used because of parameter parsing. The current package doesn't work without it.
About VCRedist, I don't know if you followed but latest few versions are NOT THE SAME as previous versions and require vcredist, which is noted in the installer name. 

> Yes, I know --ignoredependencies parameter. And I can success install HTML-Tidy with this parameter (example).

Meh, it works on my computer case ? AV comes preinstalled with bunch of stuff. You probably have dependencies in the system there.

**Comment by majkinetor** [comment]
BTW, there are no 6 deps, only 1 dep to vcredist. The fact that this one uses bunch of others is something you want to thank their respective authors really - when you move your build from AV somewhere else (or use the same technique elsewhere) you will be happy that the system is robust and just works. This methodology means that it usually brings few more things with itself.
