### ISSUE TITLE
(new package) tagscanner

### ISSUE THREAD

**Issue by majkinetor** [majkinetor/au-packages#78]
Original located here: https://github.com/niks255/ChocolateyPackages/tree/master/TagScanner

Tasks:

- [x] Modernize
- [x] AU script
- [x] Embedding package
- [ ] Making 2 streams eventually (portable & installer)

/cc @niks255

**Comment by niks255** [comment]
There already is a portable package. I'm gonna add you as a maintainer to that one as well.

**Comment by majkinetor** [comment]
Sure, not sure if I am going to do it tho. I just checked, and I don't see any benefit of portable version, I can create shim to installed version for the same effect. 

On the other hand, its not nice to leave you with half of the thing so I will think about it, given I have a little time for this. I don't personally use portable packages nowdays, generally. That was common in previous century. 

On unrelated note, Uninstaller, does it have unlimited trial ? If so, I can take that one too :) I searched for for active app that can trace installers but I can't tolerate any limitations.

**Comment by niks255** [comment]
Well, for one thing, portable package does not require admin rights to install. For some reason people really like that. It might be useful in some restricted environment.
I think we should keep both.
Uninstall tool has a limited trial, after that you have to buy it. This package is useful for easy install and updates, so that's about it.

**Comment by majkinetor** [comment]
> Well, for one thing, portable package does not require admin rights to install.

Yes, generally, but is that so in context of Chocolatey ? How many people are using  non admin choco install ?

/cc @ferventcoder 

> Uninstall tool has a limited trial, after that you have to buy it. 

Can you still use the tool after trial, like for example Total Commander ?

**Comment by niks255** [comment]
I don't know how many people use non admin choco install. But I'm pretty sure that chocolatey has such ability for a reason. So, I thought it would be nice to have a portable package for non-admin installations.

I'm pretty sure you can't use uninstall tool after trial has expired. I haven't tried it though.

**Comment by niks255** [comment]
Also, that portable package has 652 downloads as of now, so it is used by people. That's enough for me to keep that package.

**Comment by majkinetor** [comment]
```powershell
master~> Test-Package -Install -Uninstall

Package info
  Path:         C:\Work\au-packages\tagscanner\tagscanner.6.0.28.nupkg
  Name:         tagscanner
  Version:      6.0.28

Testing package install
Installing the following packages:
tagscanner
By installing you accept licenses for the packages.

tagscanner v6.0.28 (forced)
tagscanner package files install completed. Performing other installation steps.
Installing tagscanner...
tagscanner has been installed.
tagscanner installed to 'C:\Program Files (x86)\TagScanner'
tagscanner registered as tagscanner
 The install of tagscanner was successful.
  Software installed to 'C:\Program Files (x86)\TagScanner\'

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Testing package uninstall
Uninstalling the following packages:
tagscanner

tagscanner v6.0.28
Uninstalling tagscanner...
0
tagscanner has been uninstalled.
 Running auto uninstaller...
 Skipping auto uninstaller - 'TagScanner 6.0.28' appears to have been uninstalled already by other means.
 tagscanner has been successfully uninstalled.

Chocolatey uninstalled 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

**Comment by majkinetor** [comment]
The installer is finished. I will leave this open until I find out what to do with the portable package

**Comment by majkinetor** [comment]
No time for portable ATM so closing.
