### ISSUE TITLE
(gitlab-runner) Runner starts twice on first reboot

### ISSUE THREAD

**Issue by jrob** [majkinetor/au-packages#84]
## Problem

When installing with autologon, two instance of the runner start after the first reboot. Subsequent reboots behave as expected.

## Expected outcome

There is only one gitlab-runner instance running.

## Enviroment

Windows 2016 running in AWS.

## Install Command

```powershell
choco install -y gitlab-runner --package-parameters='"/Autologon:<username>:<password>"'
Restart-Computer
```

## Suspected code and potential fix

Change

https://github.com/majkinetor/au-packages/blob/ac38740e8045d4ce7e61ebb476d9a7da0d566241/gitlab-runner/tools/chocolateyInstall.ps1#L59

to

```powershell
Set-AutoLogon $Username $Password`
```

## Workaround

Call

```powershell
choco install -y gitlab-runner --package-parameters='"/Autologon:<username>:<password>"'
Remove-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce" "Set-Autologon"
Restart-Computer
```

**Comment by majkinetor** [comment]
Yeah, nice find. Please PR fix.

**Comment by majkinetor** [comment]
Hm... I thought this is about something else. I need to confirm this, I am not sure how is this possible.

**Comment by majkinetor** [comment]
There is nothing to start runner if this is not done. Service and autolad are exclusive. I wonder what starts the runner in your case ?

**Comment by jrob** [comment]
I believe it's being started by the scheduled task. The RunOnce is redundant.

https://github.com/majkinetor/au-packages/blob/ac38740e8045d4ce7e61ebb476d9a7da0d566241/gitlab-runner/tools/chocolateyInstall.ps1#L70

**Comment by majkinetor** [comment]
Yeah, right, forgot about that.  Thx for report.

**Comment by majkinetor** [comment]
Not releasing now, gitlab-runner updates frequently so it will be available on next release.
