### ISSUE TITLE
(plantuml) Does not install with multiple  javaw.exe on PATH

### ISSUE THREAD

**Issue by majkinetor** [majkinetor/au-packages#85]
http://disq.us/p/1sc998h
> PlantUML 1.2018.5 do not install by multi javaw.exe
> see https://gist.github.com/tsuyoshicho/574c5dc5b4c53f53ed5ef9a27325857a
> need gcm for select-object filter(1 as object,multi as array ; select first?)

**Comment by majkinetor** [comment]
@tsuyoshichotsuyoshicho

The problem is deciding which `javaw` to use.  Can you tell me when you just type javaw in console, which one from the 3 you have is started. It should be the one that is first on the PATH, but please double check it - I think there is possibility that the last one will be used since its x64.

**Comment by tsuyoshicho** [comment]
I'm sorry, that environment has collapsed. (For installation)

Therefore, we can not confirm directly ...
